### ISSUE TITLE
Perbedaan folder train dan val

### ISSUE THREAD

**Issue by aditiyaa97** [fatchur/Simple-Tensor#17]
Mas Fatchur saya ingin bertanya.  contoh gambar seperti apa yang dapat dibedakan dataset untuk folder train dan folder val? Apakah folder val itu dataset yang real dan kualitasnya baik.

Terima Kasih

**Comment by fatchur** [comment]
@aditiyaa97 coba kamu pelajari dulu tentang dasar machine learning, mengapa ada folder training dan validasi.

banyak course di internet
